### ISSUE TITLE
Module broken on 32-bit servers

### ISSUE THREAD

**Issue by Andrew-Eathan** [Earu/gm_asc#1]
`lua/autorun/server/relay.lua:1: Couldn't load module library! (stuff/garrysmod/lua/bin/gmsv_asc_linux.dll: undefined symbol: g_pMemAlloc)`

**Comment by Earu** [comment]
Hey, I didn't test for x86 and I don't plan on supporting x86 anyway, as x64 is more stable than ever nowadays.

**Comment by Andrew-Eathan** [comment]
alright, understandable
